export const UPDATE_PROFILE_REQUEST = "profile/UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "profile/UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "profile/UPDATE_PROFILE_FAILURE";

export const DELETE_PHOTO_REQUEST = "profile/DELETE_PHOTO_REQUEST";
