export const FETCH_LAST_COMMENTS_REQUEST =
  "comments/FETCH_LAST_COMMENTS_REQUEST";
export const FETCH_LAST_COMMENTS_SUCCESS =
  "comments/FETCH_LAST_COMMENTS_SUCCESS";
export const FETCH_LAST_COMMENTS_FAILURE =
  "comments/FETCH_LAST_COMMENTS_FAILURE";

export const SEND_COMMENT_REQUEST = "comments/SEND_COMMENT_REQUEST";
export const SEND_COMMENT_SUCCESS = "comments/SEND_COMMENT_SUCCESS";
export const SEND_COMMENT_FAILURE = "comments/SEND_COMMENT_FAILURE";
